#!/bin/bash

case `basename $1` in
    *.log)
        ;;
    *)
        head -n 1 "$1" | grep '#!/bin/bash\|#!/bin/sh' > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize -O encoding=utf-8 -O style=monokai -f terminal256 -l sh "$1"
        else
            pygmentize -O encoding=utf-8 -O style=monokai -f terminal256 -g "$1"
        fi
        ;;
esac
